import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Nav from './components/nav/Nav'
import Footer from './components/footer/Footer'

const nunito = Nunito({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'E-Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className} text-black`}>

        <div className="flex flex-col min-h-screen">
          <Nav />
          <main className="flex-grow"> {children} </main>
          <Footer />
        </div>

      </body>
    </html>
  )
}
